import Link from 'next/link';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms & Conditions — DREAM Discovery',
  description: 'Terms and Conditions for DREAM Discovery by Ethenta.',
};

const EFFECTIVE_DATE = '1 March 2025';
const COMPANY_NAME = 'Ethenta Ltd';
const COMPANY_ADDRESS = 'England and Wales';
const CONTACT_EMAIL = 'legal@ethenta.com';
const PLATFORM_NAME = 'DREAM Discovery';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <div className="max-w-4xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="mb-12">
          <Link href="/login" className="text-sm text-slate-500 hover:text-slate-700 mb-6 inline-block">
            ← Back to Sign In
          </Link>
          <h1 className="text-4xl font-bold text-slate-900 mt-4">Terms &amp; Conditions</h1>
          <p className="text-slate-500 mt-2 text-sm">
            {PLATFORM_NAME} — Platform Agreement &nbsp;·&nbsp; Effective {EFFECTIVE_DATE}
          </p>
          <div className="mt-4 p-4 bg-amber-50 border border-amber-200 rounded-lg text-sm text-amber-800">
            <strong>Important:</strong> By accessing or using {PLATFORM_NAME}, you agree to be bound by these Terms &amp; Conditions. If you do not agree, please do not use the platform.
          </div>
        </div>

        <div className="prose prose-slate max-w-none space-y-10">
          {/* 1 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">1. Definitions</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p><strong>"Agreement"</strong> means these Terms &amp; Conditions together with any applicable Order Form or Subscription Agreement.</p>
              <p><strong>"Customer"</strong> means the organisation or individual that has subscribed to or been granted access to the Platform.</p>
              <p><strong>"Platform"</strong> means {PLATFORM_NAME}, the AI-powered enterprise discovery and decision-intelligence software operated by {COMPANY_NAME}.</p>
              <p><strong>"User"</strong> means any individual authorised by the Customer to access the Platform under the Customer's account.</p>
              <p><strong>"Data"</strong> means any content, text, audio, responses, workshop outputs, or other information uploaded, generated, or processed through the Platform.</p>
              <p><strong>"AI Output"</strong> means any analysis, synthesis, insight, recommendation, or other content generated by the Platform's artificial intelligence or machine learning components.</p>
              <p><strong>"Subscription"</strong> means the licence to access and use the Platform for a defined period as set out in the applicable Order Form.</p>
            </div>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">2. Licence Grant</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>Subject to payment of all applicable Subscription fees and compliance with this Agreement, {COMPANY_NAME} grants the Customer a limited, non-exclusive, non-transferable, non-sublicensable licence to access and use the Platform solely for the Customer's internal business purposes during the Subscription term.</p>
              <p>The licence does not include the right to: (a) copy, modify, or create derivative works of the Platform; (b) reverse-engineer, decompile, or disassemble any part of the Platform; (c) access the Platform to build a competing product or service; or (d) permit access to any third party other than authorised Users.</p>
            </div>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">3. User Accounts &amp; Access</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>The Customer is responsible for: (a) ensuring all Users comply with this Agreement; (b) maintaining the confidentiality of all login credentials; (c) promptly notifying {COMPANY_NAME} of any unauthorised access or security breach; and (d) all activity that occurs under the Customer's account.</p>
              <p>Users must be at least 18 years of age and authorised by the Customer organisation. {COMPANY_NAME} reserves the right to suspend or terminate any account that it reasonably believes is being used in violation of this Agreement.</p>
              <p>The number of permitted Users is limited to the seat count specified in the applicable Subscription. Additional seats must be purchased prior to granting access to additional Users.</p>
            </div>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">4. Acceptable Use</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>Users must not use the Platform to: (a) upload, transmit, or process any content that is unlawful, defamatory, discriminatory, or that infringes any third-party intellectual property rights; (b) circumvent any security or access-control mechanisms; (c) conduct any automated scraping, crawling, or data extraction; (d) transmit malicious code, viruses, or harmful content; or (e) process special categories of personal data (as defined under applicable data protection law) unless expressly agreed in writing by {COMPANY_NAME}.</p>
              <p>{COMPANY_NAME} reserves the right to remove any Data that violates this section and to suspend access pending investigation of a suspected violation.</p>
            </div>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">5. Data Processing &amp; Privacy</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p><strong>5.1 Data Controller / Processor.</strong> The Customer acts as the Data Controller for any personal data processed through the Platform. {COMPANY_NAME} acts as a Data Processor and will process personal data only in accordance with the Customer's documented instructions and applicable data protection law (including the UK GDPR and, where applicable, the EU GDPR).</p>
              <p><strong>5.2 Data Processing Agreement.</strong> Where required by applicable law, a Data Processing Agreement ("DPA") will be entered into by the parties. The DPA forms part of this Agreement. Where no separate DPA is executed, the data processing provisions in {COMPANY_NAME}'s standard DPA (available on request) shall apply.</p>
              <p><strong>5.3 Data Location.</strong> Customer Data is stored on secure cloud infrastructure. {COMPANY_NAME} will not transfer Customer Data outside the European Economic Area or the United Kingdom without the Customer's prior written consent, unless required by applicable law.</p>
              <p><strong>5.4 Retention.</strong> {COMPANY_NAME} will retain Customer Data for the duration of the Subscription and for up to 90 days after expiry or termination, after which it will be securely deleted unless the Customer requests earlier deletion or extended retention under a separate agreement.</p>
              <p><strong>5.5 Security.</strong> {COMPANY_NAME} maintains commercially reasonable technical and organisational measures to protect Customer Data against unauthorised access, disclosure, alteration, or destruction, including encryption at rest and in transit, access controls, and regular security reviews.</p>
            </div>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">6. AI Processing &amp; Output Disclaimer</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p><strong>6.1 Nature of AI Outputs.</strong> The Platform uses artificial intelligence and large language models to generate analyses, insights, recommendations, and other content ("AI Outputs"). AI Outputs are probabilistic in nature and may not always be accurate, complete, or appropriate for the Customer's specific circumstances.</p>
              <p><strong>6.2 No Professional Advice.</strong> AI Outputs do not constitute legal, financial, strategic, medical, regulatory, or other professional advice. The Customer is solely responsible for evaluating AI Outputs and making any decisions based upon them. {COMPANY_NAME} recommends that AI Outputs be reviewed by qualified professionals before being acted upon.</p>
              <p><strong>6.3 Third-Party AI Models.</strong> The Platform may use third-party AI services (including but not limited to OpenAI's API). Customer Data submitted to the Platform may be processed by such third-party AI providers in accordance with their respective terms of service. {COMPANY_NAME} takes reasonable steps to ensure such providers maintain appropriate data protection standards.</p>
              <p><strong>6.4 Accuracy.</strong> {COMPANY_NAME} does not warrant that AI Outputs will be error-free, uninterrupted, or fit for any particular purpose. The Customer accepts full responsibility for verifying the accuracy and relevance of any AI Output before relying upon it.</p>
            </div>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">7. Intellectual Property</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p><strong>7.1 Platform IP.</strong> {COMPANY_NAME} retains all intellectual property rights in and to the Platform, including its software, algorithms, methodologies, user interface, and all AI models and training. Nothing in this Agreement transfers any Platform IP to the Customer.</p>
              <p><strong>7.2 Customer Data.</strong> The Customer retains all intellectual property rights in Customer Data. The Customer grants {COMPANY_NAME} a limited, non-exclusive licence to process Customer Data solely as necessary to provide the Platform services.</p>
              <p><strong>7.3 AI Outputs.</strong> Subject to payment of all fees, AI Outputs generated from the Customer's Data are assigned to the Customer for use in its internal business operations. {COMPANY_NAME} retains the right to use anonymised, aggregated insights derived from Customer Data to improve the Platform, provided such use does not identify the Customer or any individual.</p>
              <p><strong>7.4 Feedback.</strong> Any feedback, suggestions, or improvement ideas provided by the Customer regarding the Platform may be used by {COMPANY_NAME} without restriction or compensation.</p>
            </div>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">8. Confidentiality</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>Each party agrees to keep confidential all non-public information disclosed by the other party that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and circumstances of disclosure ("Confidential Information"). This obligation does not apply to information that: (a) is or becomes publicly known through no fault of the receiving party; (b) was already known to the receiving party prior to disclosure; (c) is independently developed by the receiving party; or (d) is required to be disclosed by law or regulatory authority.</p>
              <p>Each party will use the other's Confidential Information only to the extent necessary to perform its obligations or exercise its rights under this Agreement and will protect it with at least the same degree of care it uses for its own confidential information (but no less than reasonable care).</p>
            </div>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">9. Fees &amp; Payment</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>Subscription fees are as set out in the applicable Order Form. Unless otherwise agreed: (a) fees are invoiced annually in advance; (b) payment is due within 30 days of invoice; (c) all fees are exclusive of VAT or applicable taxes; (d) fees are non-refundable except as expressly set out herein; and (e) {COMPANY_NAME} may suspend access to the Platform if fees remain unpaid for more than 30 days after the due date.</p>
              <p>{COMPANY_NAME} reserves the right to adjust Subscription fees on not less than 60 days' written notice before the start of any renewal term.</p>
            </div>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">10. Service Levels &amp; Availability</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>{COMPANY_NAME} will use commercially reasonable efforts to ensure the Platform is available 99.5% of the time in any calendar month, excluding scheduled maintenance windows (notified at least 48 hours in advance) and circumstances beyond {COMPANY_NAME}'s reasonable control. {COMPANY_NAME} does not guarantee uninterrupted or error-free operation of the Platform.</p>
              <p>The Customer's sole remedy for a breach of availability commitments is a pro-rata service credit not exceeding one month's Subscription fees, applied to the next invoice, provided the Customer reports the downtime in writing within 10 business days of the incident.</p>
            </div>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">11. Warranties &amp; Disclaimers</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>{COMPANY_NAME} warrants that: (a) it has the right to grant the licence in clause 2; and (b) the Platform will perform materially in accordance with any documentation provided by {COMPANY_NAME}.</p>
              <p>Except as expressly stated in this Agreement, the Platform is provided "as is" and "as available". {COMPANY_NAME} expressly disclaims all other warranties, whether express, implied, statutory, or otherwise, including any implied warranties of merchantability, fitness for a particular purpose, title, or non-infringement.</p>
            </div>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">12. Limitation of Liability</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p><strong>12.1 Exclusion of consequential loss.</strong> To the maximum extent permitted by applicable law, neither party will be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to this Agreement, including loss of profit, loss of revenue, loss of data, loss of goodwill, or business interruption, regardless of whether such damages were foreseeable or whether the party was advised of their possibility.</p>
              <p><strong>12.2 Aggregate cap.</strong> Each party's total aggregate liability to the other arising out of or in connection with this Agreement in any 12-month period shall not exceed the greater of: (a) the total Subscription fees paid or payable by the Customer in the 12 months immediately preceding the event giving rise to the claim; or (b) £10,000.</p>
              <p><strong>12.3 Exceptions.</strong> Nothing in this Agreement limits or excludes either party's liability for: (a) death or personal injury caused by negligence; (b) fraud or fraudulent misrepresentation; or (c) any liability that cannot be excluded or limited by applicable law.</p>
            </div>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">13. Indemnification</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>The Customer will indemnify, defend, and hold harmless {COMPANY_NAME} and its officers, directors, employees, and agents from and against any claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising out of or relating to: (a) the Customer's or any User's use of the Platform in breach of this Agreement; (b) any Customer Data that infringes a third party's intellectual property rights or violates applicable law; or (c) the Customer's violation of any applicable laws or regulations.</p>
            </div>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">14. Term &amp; Termination</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>This Agreement commences on the date the Customer first accesses the Platform and continues for the initial Subscription term specified in the Order Form, automatically renewing for successive 12-month periods unless either party gives not less than 30 days' written notice before the end of the then-current term.</p>
              <p>Either party may terminate this Agreement immediately on written notice if: (a) the other party materially breaches this Agreement and fails to remedy the breach within 30 days of receiving written notice; or (b) the other party becomes insolvent, makes a general assignment for the benefit of creditors, or has a receiver, administrator, or liquidator appointed.</p>
              <p>Upon termination: (a) all licences granted herein immediately cease; (b) each party will return or destroy the other's Confidential Information; and (c) the Customer may request a data export within 30 days after which {COMPANY_NAME} will securely delete Customer Data. Clauses 7, 8, 12, 13, and 16 survive termination.</p>
            </div>
          </section>

          {/* 15 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">15. Changes to This Agreement</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>{COMPANY_NAME} may update these Terms &amp; Conditions from time to time. Where changes are material, {COMPANY_NAME} will provide not less than 30 days' notice via email to the Customer's registered email address or via a notice within the Platform. Continued use of the Platform after the effective date of any changes constitutes acceptance of the revised Terms. If the Customer does not accept the changes, it may terminate its Subscription on written notice before the effective date.</p>
            </div>
          </section>

          {/* 16 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">16. Governing Law &amp; Dispute Resolution</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p>This Agreement is governed by and construed in accordance with the laws of England and Wales. Any dispute arising out of or in connection with this Agreement shall first be referred to senior representatives of each party for good-faith negotiation. If the dispute is not resolved within 30 days of referral, either party may refer it to the exclusive jurisdiction of the courts of {COMPANY_ADDRESS}.</p>
            </div>
          </section>

          {/* 17 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-800 mb-3 pb-2 border-b border-slate-200">17. General</h2>
            <div className="text-slate-600 space-y-2 text-sm leading-relaxed">
              <p><strong>Entire Agreement.</strong> This Agreement constitutes the entire agreement between the parties relating to its subject matter and supersedes all prior agreements, representations, and understandings.</p>
              <p><strong>Severability.</strong> If any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions will remain in full force and effect.</p>
              <p><strong>Waiver.</strong> No failure or delay by either party in exercising any right under this Agreement will constitute a waiver of that right.</p>
              <p><strong>Assignment.</strong> The Customer may not assign or transfer any of its rights or obligations under this Agreement without {COMPANY_NAME}'s prior written consent. {COMPANY_NAME} may assign this Agreement to an affiliate or in connection with a merger, acquisition, or sale of substantially all of its assets.</p>
              <p><strong>Force Majeure.</strong> Neither party will be liable for failure or delay in performance to the extent caused by circumstances beyond its reasonable control, including acts of God, natural disasters, war, terrorism, government action, or internet service disruptions.</p>
              <p><strong>Notices.</strong> All legal notices under this Agreement must be in writing and sent by email to {CONTACT_EMAIL} ({COMPANY_NAME}) or to the Customer's registered email address, and are effective upon confirmed receipt.</p>
            </div>
          </section>

          {/* Contact */}
          <section className="mt-12 p-6 bg-slate-100 rounded-xl border border-slate-200">
            <h2 className="text-lg font-semibold text-slate-800 mb-2">Contact Us</h2>
            <p className="text-sm text-slate-600">
              If you have any questions about these Terms &amp; Conditions, please contact us at{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-blue-600 hover:underline">{CONTACT_EMAIL}</a>.
            </p>
            <p className="text-xs text-slate-400 mt-3">
              {COMPANY_NAME} · Registered in {COMPANY_ADDRESS} · {PLATFORM_NAME} is a trading product of {COMPANY_NAME}
            </p>
          </section>
        </div>

        {/* Footer nav */}
        <div className="mt-12 pt-6 border-t border-slate-200 flex items-center justify-between text-xs text-slate-400">
          <span>© {new Date().getFullYear()} {COMPANY_NAME}. All rights reserved.</span>
          <Link href="/login" className="hover:text-slate-600">Back to Sign In →</Link>
        </div>
      </div>
    </div>
  );
}
