/**
 * seed-joair-dense-nodes.ts
 *
 * Generates 1,920 AI-driven hemisphere nodes for the Jo Air live workshop:
 *   - 640 nodes per phase (REIMAGINE / CONSTRAINTS / DEFINE_APPROACH)
 *   - 5 questions × 8 lenses × 16 nodes per combination
 *   - Content generated by GPT-4o-mini in parallel batches of 10
 *
 * Also seeds a LiveSessionVersion with a complete "facilitated" session state.
 * Journey stages and actors are read from the workshop blueprint (set by the
 * research agent) — NOT hardcoded. Interactions are pre-seeded using the
 * blueprint actor labels and stage names so the journey map loads correctly.
 *
 * Run: npx tsx scripts/seed-joair-dense-nodes.ts
 */

import OpenAI from 'openai';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const WORKSHOP_ID = 'cmmezcr7r0001jj04vc6fiqdw';
const MODEL = 'gpt-4o-mini';
const BATCH_SIZE = 10;
const NODES_PER_CHUNK = 16;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function uid(): string {
  return `${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

function nanoid8(): string {
  return Math.random().toString(36).slice(2, 10);
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const SPEAKERS = [
  'Sarah Morrison', 'James Whitfield', 'Rachel Hughes', 'David Palmer', 'Fiona Lawson',
  'Tom Hendricks', 'Angela Ward', 'Chris Barker', 'Priya Sharma', "Mark O'Brien",
  'Katherine James', 'Jamie Walsh', 'Raj Patel', 'Nathan Hughes', 'Ben Torres',
  'Louise Carter', 'Daniel Cooper', 'Jade Robinson', 'Ryan Mitchell', 'Amy Fletcher',
  'Aisha Okafor', 'Simon Reed', 'Claire Donovan', 'Emma Fitzgerald', "Liam O'Connor",
];

const LENSES = [
  'Customer Experience',
  'People & Workforce',
  'Operations',
  'Technology',
  'Training & Capability',
  'Regulation & Compliance',
  'Organisation & Leadership',
  'Culture',
] as const;
type Lens = typeof LENSES[number];

type Phase = 'REIMAGINE' | 'CONSTRAINTS' | 'DEFINE_APPROACH';

type ChunkSpec = {
  phase: Phase;
  questionIndex: number;
  questionTopic: string;
  lens: Lens;
};

// ─── Phase / Question structure ───────────────────────────────────────────────

const PHASE_QUESTIONS: Record<Phase, string[]> = {
  REIMAGINE: [
    'Customer experience during flight disruption events — personalisation, proactive comms, Gold/Platinum treatment, disruption playbooks',
    'Agent empowerment and decision authority — trust-based autonomy, real-time authority matrix, removing supervisor bottleneck',
    'Omnichannel unification and single customer record — seamless channel switching, unified agent desktop, no context loss',
    'AI-augmented operations and predictive demand — AI co-pilot for agents, real-time demand forecasting, intelligent routing',
    'World-class BPO parity — Manila, Krakow, Cape Town, Hyderabad operating as equals with the same tools and authority',
  ],
  CONSTRAINTS: [
    'System fragmentation and data silos — 8 disconnected legacy systems with no unified customer record or API layer',
    'Culture of control and agent disempowerment — 30% escalation rate, rigid scripting, no decision authority, supervisors as bottleneck',
    'Workforce model and capacity planning failures — Erlang C model breakdown during disruptions, high attrition, WFM tool gaps, skills mismatches',
    'Regulatory and compliance blockers — GDPR localisation slowing AI adoption, PCI-DSS restrictions, EU261 fully manual claim processing',
    'BPO structural and contractual barriers — vendor vs. partner mentality, tech exclusion, siloed standards, different training and authority',
  ],
  DEFINE_APPROACH: [
    'Technology integration roadmap — API middleware layer, Verint upgrade, CRM consolidation onto a single platform with real-time data',
    'People and capability programme — career architecture for agents, authority matrix, coaching culture for supervisors, structured upskilling',
    'Operating model redesign — FCR as primary metric replacing AHT, flat hierarchy, decision rights expansion, governance and accountability framework',
    'Compliance automation — EU261 auto-claim processing, GDPR privacy-by-design in the new tech stack, PCI-DSS tokenization enabling AI tools',
    'BPO partnership model — embedded team model replacing vendor contracts, unified performance standards, shared tech stack rollout to all sites',
  ],
};

function nodeTypeForPhaseAndIndex(phase: Phase, index: number): string {
  if (phase === 'REIMAGINE') return index <= 12 ? 'VISION' : 'INSIGHT';
  if (phase === 'CONSTRAINTS') return index <= 10 ? 'CONSTRAINT' : 'RISK';
  return index <= 8 ? 'ENABLER' : 'ACTION'; // DEFINE_APPROACH
}

const WORKSHOP_CONTEXT = `Jo Air is a major airline transforming its customer contact centre. The end goal is to move from a fragmented, reactive, compliance-driven operation to a proactive, personalised, AI-augmented service that resolves issues faster, empowers agents, cuts failure demand, and delivers consistent outcomes across all channels and BPO sites (Manila, Krakow, Cape Town, Hyderabad). Key context: 8 disconnected legacy systems, 30% escalation rate, Gold/Platinum loyalty tiers, EU261 compensation regulation, GDPR, PCI-DSS, Verint for WFM, Erlang C capacity model, cargo and freight division, inbound and outbound contact, ~2,000 FTE across internal and BPO teams.`;

// ─── AI content generation ────────────────────────────────────────────────────

async function generateChunk(spec: ChunkSpec, attempt = 1): Promise<string[]> {
  const { phase, questionTopic, lens } = spec;

  const phaseInstruction =
    phase === 'REIMAGINE'
      ? 'These are aspirational VISION statements — participants imagining the ideal future state. Use language like "In the world we want...", "Imagine if...", "The goal is...", "We should be able to...".'
      : phase === 'CONSTRAINTS'
      ? 'These are CONSTRAINT/RISK statements — participants voicing real blockers and frustrations. Use language like "The reality is...", "We\'re held back by...", "The problem is...", "What frustrates me...".'
      : 'These are ENABLER/ACTION statements — participants describing concrete solutions and ownership. Use language like "The first step is...", "We need to invest in...", "My team will...", "Within 90 days..."';

  const prompt = `You are generating synthetic participant responses for a live workshop facilitation tool.

${WORKSHOP_CONTEXT}

Current workshop phase: ${phase}
Question focus: ${questionTopic}
Lens perspective: ${lens}

${phaseInstruction}

Generate exactly ${NODES_PER_CHUNK} unique participant statements spoken from the ${lens} perspective about this question.

Rules:
- Each statement is 1-3 sentences, in first-person, as if spoken aloud in a workshop
- Use specific Jo Air context: mention sites (Manila/Krakow/Cape Town/Hyderabad), metrics (FCR, AHT, 30% escalation), systems (Verint, 8 legacy systems), regulations (EU261, GDPR, PCI-DSS), tiers (Gold/Platinum), terms (disruption playbook, Erlang C, authority matrix) where natural
- Statements must be varied — no two should be the same idea reworded
- Build progressively: earlier statements are broader/strategic, later ones are more specific/operational
- All statements must be coherent with the ${lens} lens perspective

Return ONLY a valid JSON array of exactly ${NODES_PER_CHUNK} strings. No markdown, no keys, no explanation.`;

  try {
    const res = await openai.chat.completions.create({
      model: MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.85,
      response_format: { type: 'json_object' },
    });

    const raw = res.choices[0]?.message?.content ?? '[]';
    // The model may wrap in a key — try to extract array
    const parsed: unknown = JSON.parse(raw);
    let arr: string[] = [];
    if (Array.isArray(parsed)) {
      arr = parsed as string[];
    } else if (parsed && typeof parsed === 'object') {
      const vals = Object.values(parsed as Record<string, unknown>);
      if (vals.length === 1 && Array.isArray(vals[0])) arr = vals[0] as string[];
      else arr = vals.flatMap(v => Array.isArray(v) ? v : [String(v)]) as string[];
    }

    if (arr.length < NODES_PER_CHUNK) {
      // Pad with placeholders if short
      while (arr.length < NODES_PER_CHUNK) {
        arr.push(`[${phase} – ${lens} perspective on ${questionTopic.slice(0, 40)}]`);
      }
    }
    return arr.slice(0, NODES_PER_CHUNK).map(String);
  } catch (err) {
    if (attempt < 2) {
      console.warn(`  ⚠ Retrying chunk ${phase}[Q${spec.questionIndex}][${lens}]...`);
      await new Promise(r => setTimeout(r, 1500));
      return generateChunk(spec, 2);
    }
    console.error(`  ✗ Chunk failed after retry: ${phase}[Q${spec.questionIndex}][${lens}]`, err);
    // Return placeholders so overall run continues
    return Array.from({ length: NODES_PER_CHUNK }, (_, i) =>
      `[${phase} Q${spec.questionIndex} ${lens} node ${i + 1} — generation failed]`
    );
  }
}

// ─── Session version generation ───────────────────────────────────────────────

type SessionContent = {
  mainQuestions: Array<{
    id: string;
    text: string;
    purpose: string;
    grounding: string;
    lens: string | null;
    order: number;
  }>;
  completedPads: string[][];  // [Q0[], Q1[], Q2[], Q3[]] — 3 prompts each
  activePads: string[];       // Q4 — 2 active
  coveredPad: string;         // Q4 — 1 covered
};

async function generateSessionContent(): Promise<SessionContent> {
  const prompt = `You are generating facilitation content for a Jo Air contact centre transformation workshop.

${WORKSHOP_CONTEXT}

The session is in the DEFINE_APPROACH phase — designing concrete solutions. Generate:

1. "mainQuestions": exactly 5 facilitation questions for this phase (one per topic below):
   Q0: Technology integration — unifying 8 systems via API middleware, Verint upgrade, CRM consolidation
   Q1: People and capability — career architecture, authority matrix, coaching culture
   Q2: Operating model — FCR as primary metric, flat hierarchy, decision rights, governance
   Q3: Compliance automation — EU261, GDPR privacy-by-design, PCI-DSS tokenization
   Q4: BPO partnership — embedded team model, unified standards, shared tech stack

   Each question object: { "id": "<8-char alphanumeric>", "text": "<the main question>", "purpose": "<why this matters, 1 sentence>", "grounding": "<how it connects to workshop findings, 1 sentence>", "lens": "<dominant lens: Technology|People|Organisation|Regulation|null>", "order": <0-4> }

2. "completedPads": for Q0–Q3, a sub-array of exactly 3 sub-question strings that a facilitator would explore under that main question. These should be probing follow-up questions (not statements).
   Format: [ [q0_sub1, q0_sub2, q0_sub3], [q1_sub1, ...], [q2_sub1, ...], [q3_sub1, ...] ]

3. "activePads": exactly 2 sub-question strings for Q4 (BPO partnership) — currently being explored.

4. "coveredPad": exactly 1 string — a sub-question for Q4 that was already covered earlier in the discussion.

Return ONLY valid JSON with keys: mainQuestions, completedPads, activePads, coveredPad.`;

  try {
    const res = await openai.chat.completions.create({
      model: MODEL,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      response_format: { type: 'json_object' },
    });
    const raw = res.choices[0]?.message?.content ?? '{}';
    return JSON.parse(raw) as SessionContent;
  } catch {
    // Fallback with decent content
    return {
      mainQuestions: [
        { id: nanoid8(), text: 'How do we sequence the consolidation of our 8 legacy systems into a unified API layer?', purpose: 'Define the technology integration roadmap', grounding: 'System fragmentation was the top-rated blocker in discovery interviews', lens: 'Technology', order: 0 },
        { id: nanoid8(), text: 'What does a new career architecture look like for contact centre agents, and how do we build the coaching capability to sustain it?', purpose: 'Design the people and capability programme', grounding: 'Agent disempowerment and attrition were recurring themes across all sessions', lens: 'People', order: 1 },
        { id: nanoid8(), text: 'If FCR replaces AHT as our primary success metric, what governance and decision rights changes need to follow?', purpose: 'Redesign the operating model around outcomes', grounding: 'Current AHT focus drives wrong behaviours identified in discovery', lens: 'Organisation', order: 2 },
        { id: nanoid8(), text: 'Which compliance obligations can we automate, and what does a privacy-by-design approach mean for our new tech stack?', purpose: 'Turn compliance from a blocker into an enabler', grounding: 'EU261, GDPR and PCI-DSS were identified as blockers to AI adoption', lens: 'Regulation', order: 3 },
        { id: nanoid8(), text: 'What needs to change in our BPO contracts and governance to move from a vendor to a true embedded-team model?', purpose: 'Redesign the BPO partnership for parity and shared ownership', grounding: 'BPO sites rated lowest for empowerment and access to tools in discovery', lens: 'Organisation', order: 4 },
      ],
      completedPads: [
        ['What is the minimum viable API layer to connect the 8 systems?', 'Which system should be the master customer record?', 'How do we handle data migration risk during the Verint upgrade?'],
        ['What authority can we safely delegate to agents in the first 90 days?', 'How do we redesign the supervisor role in a flat model?', 'What does the career path look like from Agent to Senior Agent to Team Lead?'],
        ['How do we redefine targets when AHT is no longer primary?', 'Who owns the FCR governance framework?', 'What dashboard does a contact centre manager need in the new model?'],
        ['Can EU261 claim processing be fully automated, or only partially?', 'What does privacy-by-design require of our CRM vendor?', 'How do we get PCI-DSS sign-off for AI-assisted payment queries?'],
      ],
      activePads: [
        'What SLA changes do we need in BPO contracts to enforce unified performance standards?',
        'How do we roll out the same tech stack to Manila and Krakow within 12 months?',
      ],
      coveredPad: 'What does "embedded team" mean in practice for the Cape Town site?',
    };
  }
}

// ─── Build StickyPad objects ──────────────────────────────────────────────────

type StickyPadLike = {
  id: string;
  type: string;
  prompt: string;
  signalStrength: number;
  provenance: { triggerType: string; sourceNodeIds: string[]; description: string };
  createdAtMs: number;
  status: string;
  snoozedUntilMs: null;
  source: string;
  questionId: string | null;
  grounding: string | null;
  coveragePercent: number;
  coverageState: string;
  lens: string | null;
  mainQuestionIndex: number | null;
  journeyGapId: null;
  padLabel: string | null;
};

function makePad(
  prompt: string,
  coverageState: 'active' | 'covered' | 'queued',
  questionId: string,
  mainQuestionIndex: number,
  lens: string | null,
  createdAtMs: number,
): StickyPadLike {
  return {
    id: `pad_${nanoid8()}`,
    type: 'CLARIFICATION',
    prompt,
    signalStrength: 0.7 + Math.random() * 0.25,
    provenance: {
      triggerType: 'FACILITATOR_PROMPT',
      sourceNodeIds: [],
      description: 'Prep-generated sub-question for this main question',
    },
    createdAtMs,
    status: 'active',
    snoozedUntilMs: null,
    source: 'prep',
    questionId,
    grounding: null,
    coveragePercent: coverageState === 'covered' ? 85 + Math.floor(Math.random() * 15) : 20,
    coverageState,
    lens,
    mainQuestionIndex,
    journeyGapId: null,
    padLabel: null,
  };
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🚀 Jo Air dense node seeder — AI-powered\n');

  if (!process.env.OPENAI_API_KEY) {
    console.error('❌ OPENAI_API_KEY is not set. Aborting.');
    process.exit(1);
  }

  // ── Read blueprint journey data (stages + actors) from DB ────────────────────
  console.log('📖 Reading workshop blueprint for journey data...');
  const workshopData = await prisma.workshop.findUnique({
    where: { id: WORKSHOP_ID },
    select: { blueprint: true },
  });
  const blueprint = workshopData?.blueprint as {
    journeyStages?: Array<{ name: string; description: string }>;
    actorTaxonomy?: Array<{ key: string; label: string; description: string }>;
  } | null;

  const blueprintStages = blueprint?.journeyStages?.map(s => s.name) ?? [];
  const blueprintActors = (blueprint?.actorTaxonomy ?? []).map(a => ({
    name: a.label,
    role: a.description,
    mentionCount: 0, // computed below from interactions
  }));

  if (!blueprintStages.length) {
    console.error('❌ Blueprint has no journeyStages — cannot seed journey map. Run workshop prep first.');
    process.exit(1);
  }
  console.log(`   ✅ ${blueprintStages.length} stages, ${blueprintActors.length} actors from blueprint\n`);

  // ── Build the 75-chunk specification ────────────────────────────────────────
  const chunks: ChunkSpec[] = [];
  for (const [phase, questions] of Object.entries(PHASE_QUESTIONS) as [Phase, string[]][]) {
    for (let qi = 0; qi < questions.length; qi++) {
      for (const lens of LENSES) {
        chunks.push({ phase, questionIndex: qi, questionTopic: questions[qi], lens });
      }
    }
  }
  console.log(`📦 ${chunks.length} chunks to generate (${chunks.length * NODES_PER_CHUNK} nodes total)\n`);

  // ── Generate in batches of BATCH_SIZE ────────────────────────────────────────
  const allStatements: Array<{ spec: ChunkSpec; statements: string[] }> = [];
  const batches = chunk(chunks, BATCH_SIZE);

  for (let bi = 0; bi < batches.length; bi++) {
    const batch = batches[bi];
    process.stdout.write(`  Batch ${bi + 1}/${batches.length} (${batch.length} calls)... `);
    const results = await Promise.all(batch.map(spec => generateChunk(spec)));
    for (let i = 0; i < batch.length; i++) {
      allStatements.push({ spec: batch[i], statements: results[i] });
    }
    console.log('✓');
  }

  console.log(`\n✅ Generated ${allStatements.reduce((s, a) => s + a.statements.length, 0)} statements\n`);

  // ── Build nodesById for LiveWorkshopSnapshot ─────────────────────────────────
  const now = Date.now();
  let speakerIdx = 0;
  let nodeIdx = 0;

  type SnapshotNode = {
    rawText: string;
    lens: string;
    dialoguePhase: string;
    classification: { primaryType: string };
    speakerId: string;
    createdAtMs: number;
  };
  const nodesById: Record<string, SnapshotNode> = {};

  // Also build hemisphereNodes (richer format) for LiveSessionVersion
  type HemisphereNodeLike = {
    dataPointId: string;
    createdAtMs: number;
    rawText: string;
    dataPointSource: string;
    speakerId: string;
    lens: string;
    dialoguePhase: string;
    classification: {
      primaryType: string;
      confidence: number;
      keywords: string[];
      suggestedArea: string | null;
      updatedAt: string;
    };
    agenticAnalysis: null;
  };
  const hemisphereNodes: Record<string, HemisphereNodeLike> = {};

  const phaseCounts: Record<Phase, number> = { REIMAGINE: 0, CONSTRAINTS: 0, DEFINE_APPROACH: 0 };

  for (const { spec, statements } of allStatements) {
    for (let si = 0; si < statements.length; si++) {
      const id = `node_${uid()}_${nodeIdx}`;
      const speaker = SPEAKERS[speakerIdx % SPEAKERS.length];
      const primaryType = nodeTypeForPhaseAndIndex(spec.phase, si);
      const createdAtMs = now - (1200 - nodeIdx) * 30_000; // spread ~10h back

      const snapshotNode: SnapshotNode = {
        rawText: statements[si],
        lens: spec.lens,
        dialoguePhase: spec.phase,
        classification: { primaryType },
        speakerId: speaker,
        createdAtMs,
      };
      nodesById[id] = snapshotNode;

      const hemisphereNode: HemisphereNodeLike = {
        dataPointId: id,
        createdAtMs,
        rawText: statements[si],
        dataPointSource: 'capture',
        speakerId: speaker,
        lens: spec.lens,
        dialoguePhase: spec.phase,
        classification: {
          primaryType,
          confidence: 0.82 + Math.random() * 0.15,
          keywords: [],
          suggestedArea: null,
          updatedAt: new Date(createdAtMs).toISOString(),
        },
        agenticAnalysis: null,
      };
      hemisphereNodes[id] = hemisphereNode;

      phaseCounts[spec.phase]++;
      speakerIdx++;
      nodeIdx++;
    }
  }

  console.log(`📊 Node distribution:`);
  console.log(`   REIMAGINE:       ${phaseCounts.REIMAGINE}`);
  console.log(`   CONSTRAINTS:     ${phaseCounts.CONSTRAINTS}`);
  console.log(`   DEFINE_APPROACH: ${phaseCounts.DEFINE_APPROACH}`);
  console.log(`   Total:           ${nodeIdx}\n`);

  // ── Upsert LiveWorkshopSnapshot ──────────────────────────────────────────────
  console.log('💾 Upserting LiveWorkshopSnapshot...');
  const snapshotPayload = {
    v: 2,
    savedAtMs: now,
    dialoguePhase: 'DEFINE_APPROACH',
    mainQuestionIndex: 4,
    nodesById,
    cogNodes: [],
    stickyPads: [],
    completedByQuestion: [],
    signals: [],
    liveJourney: {
      stages: blueprintStages,
      actors: blueprintActors,
      interactions: [],
    },
    sessionConfidence: { overallConfidence: 0.84, categorisedRate: 0.91, lensCoverageRate: 0.88, contradictionCount: 2, stabilisedBeliefCount: 14 },
    themes: [],
    activeThemeId: null,
    lensCoverage: [],
    agentConversation: [],
    journeyCompletionState: null,
  };

  await (prisma as unknown as { liveWorkshopSnapshot: { deleteMany: (a: unknown) => Promise<unknown>; create: (a: unknown) => Promise<unknown> } })
    .liveWorkshopSnapshot.deleteMany({ where: { workshopId: WORKSHOP_ID } });

  await (prisma as unknown as { liveWorkshopSnapshot: { deleteMany: (a: unknown) => Promise<unknown>; create: (a: unknown) => Promise<{ id: string }> } })
    .liveWorkshopSnapshot.create({
      data: {
        workshopId: WORKSHOP_ID,
        name: 'Jo Air Workshop — Full Session (1,920 nodes)',
        dialoguePhase: 'DEFINE_APPROACH',
        payload: snapshotPayload,
      },
    });
  console.log('   ✅ LiveWorkshopSnapshot created\n');

  // ── Generate session content (main questions + sub-pads) ─────────────────────
  console.log('🤖 Generating session state (main questions + sub-pads)...');
  const session = await generateSessionContent();
  console.log('   ✅ Session content generated\n');

  // ── Build stickyPads + completedByQuestion ────────────────────────────────────
  const sessionNow = now - 5 * 60_000; // 5 minutes ago
  const stickyPads: StickyPadLike[] = [];
  const completedByQuestion: Array<[number, StickyPadLike[]]> = [];

  const mainQs = session.mainQuestions ?? [];
  const completedPads: string[][] = session.completedPads ?? [[], [], [], []];
  const activePadPrompts: string[] = session.activePads ?? [];
  const coveredPadPrompt: string = session.coveredPad ?? '';

  // Q0–Q3: covered sub-pads stored in completedByQuestion
  for (let qi = 0; qi <= 3; qi++) {
    const q = mainQs[qi];
    if (!q) continue;
    const prompts = completedPads[qi] ?? [];
    const qPads: StickyPadLike[] = prompts.map((prompt, pi) =>
      makePad(
        prompt,
        'covered',
        q.id,
        qi,
        q.lens ?? null,
        sessionNow - (4 - qi) * 20 * 60_000 + pi * 60_000,
      )
    );
    completedByQuestion.push([qi, qPads]);
  }

  // Q4: 1 covered + 2 active (in stickyPads)
  const q4 = mainQs[4];
  if (q4) {
    if (coveredPadPrompt) {
      stickyPads.push(makePad(coveredPadPrompt, 'covered', q4.id, 4, q4.lens ?? null, sessionNow - 10 * 60_000));
    }
    for (const prompt of activePadPrompts) {
      stickyPads.push(makePad(prompt, 'active', q4.id, 4, q4.lens ?? null, sessionNow - 5 * 60_000));
    }
  }

  // ── Upsert LiveSessionVersion ─────────────────────────────────────────────────
  console.log('💾 Upserting LiveSessionVersion...');

  await (prisma as unknown as { liveSessionVersion: { deleteMany: (a: unknown) => Promise<unknown>; create: (a: unknown) => Promise<unknown> } })
    .liveSessionVersion.deleteMany({ where: { workshopId: WORKSHOP_ID } });

  const sessionPayload = {
    v: 2,
    savedAtMs: now,
    dialoguePhase: 'DEFINE_APPROACH',
    mainQuestionIndex: 4,
    hemisphereNodes,
    cogNodes: [],
    stickyPads,
    completedByQuestion,
    signals: [],
    liveJourney: (() => {
      // Interactions use blueprint actor labels and stage names — no hardcoding.
      // Actor name mapping: old workshop-specific labels → blueprint taxonomy labels.
      // Stage name mapping: old adhoc stages → blueprint journeyStages names.
      const interactions = [
        { id: 'ji_001', actor: 'Passenger / Traveller',        stage: 'In-Flight Experience',     sentiment: 'critical',  businessIntensity: 0.9,  customerIntensity: 0.95, aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: true,  isMomentOfTruth: true,  addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 80 * 60_000, action: 'Calls to rebook after flight cancellation. Received no proactive notification — discovered the cancellation via the app 40 minutes after the event. Now 47 minutes into a call queue with no callback option.', context: 'Peak disruption, 3 flights cancelled simultaneously. Queue volumes at 2,400 contacts.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_002', actor: 'Passenger / Traveller',        stage: 'Post-Journey Support',     sentiment: 'concerned', businessIntensity: 0.7,  customerIntensity: 0.85, aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: false, isMomentOfTruth: true,  addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 78 * 60_000, action: 'Follows up to claim EU261 compensation. Process is fully manual — agent must log claim by hand and customer is told to expect 8–12 weeks for resolution. Gold member expects significantly better.', context: 'Compensation claim following disrupted flight. Agent has no automation tool for EU261 processing.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_003', actor: 'Customer Service Agent',       stage: 'In-Flight Experience',     sentiment: 'concerned', businessIntensity: 0.85, customerIntensity: 0.8,  aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: true,  isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 75 * 60_000, action: 'Handling 4 simultaneous disruption contacts with no real-time flight data on desktop. Customer on hold has more current information via the Jo Air app than the agent can access through any internal system.', context: 'Agent relying on a static disruption brief that is 22 minutes out of date. Systems are disconnected from live ops feed.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_004', actor: 'Customer Service Agent',       stage: 'Booking',                  sentiment: 'neutral',   businessIntensity: 0.4,  customerIntensity: 0.5,  aiAgencyNow: 'human',    aiAgencyFuture: 'autonomous',isPainPoint: false, isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 73 * 60_000, action: 'Handles a standard seat upgrade call. Amadeus system requires 6 separate screen interactions to complete a simple seat change. Total handle time 7 minutes for a task that should take 90 seconds.', context: 'Routine booking modification. No disruption context. System fragmentation creating unnecessary friction.', phaseAdded: 'REIMAGINE' },
        { id: 'ji_005', actor: 'Frequent Flyer Member',        stage: 'In-Flight Experience',     sentiment: 'critical',  businessIntensity: 0.9,  customerIntensity: 0.95, aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: true,  isMomentOfTruth: true,  addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 72 * 60_000, action: 'Gold member calls after connection cancelled. Placed in the same 45-minute general queue as first-time flyers. No agent visibility of tier status at the queue stage — priority routing does not exist for inbound calls.', context: 'High-value customer. Three prior disruption contacts in 12 months, each resulting in the same experience. Loyalty at risk.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_006', actor: 'Frequent Flyer Member',        stage: 'Loyalty & Future Engagement', sentiment: 'positive', businessIntensity: 0.65, customerIntensity: 0.8,  aiAgencyNow: 'assisted', aiAgencyFuture: 'autonomous',isPainPoint: false, isMomentOfTruth: true,  addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 70 * 60_000, action: 'Post-disruption, Gold member receives a proactive goodwill gesture initiated by the loyalty team — lounge access voucher and 5,000 bonus miles credited before the customer calls. Member calls to say thank you.', context: 'Rare proactive recovery initiated by the premium cabin team. Agent empowered to act without supervisor approval for this tier.', phaseAdded: 'DEFINE_APPROACH' },
        { id: 'ji_007', actor: 'Specialist Agent',             stage: 'In-Flight Experience',     sentiment: 'positive',  businessIntensity: 0.85, customerIntensity: 0.75, aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: false, isMomentOfTruth: true,  addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 68 * 60_000, action: 'Specialist agent activates the disruption playbook, rebooks 12 passengers across 3 alternative routes in under 6 minutes using elevated Amadeus authority. Premium cabin priority restored within 15 minutes of disruption alert.', context: 'Disruption specialist team — 8 agents with elevated system rights. Only team empowered to act at pace during major incidents.', phaseAdded: 'DEFINE_APPROACH' },
        { id: 'ji_008', actor: 'Team Leader / Supervisor',     stage: 'In-Flight Experience',     sentiment: 'concerned', businessIntensity: 0.85, customerIntensity: 0.7,  aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: true,  isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 65 * 60_000, action: 'Supervisor becomes a bottleneck: 30% of disruption contacts require escalation because agents lack authority to rebook independently. Handling 8 simultaneous escalations, missing SLA on 4.', context: 'Current escalation model makes supervisors the single point of authority for rebooking. Model breaks under volume.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_009', actor: 'Customer Service Agent',       stage: 'In-Flight Experience',     sentiment: 'concerned', businessIntensity: 0.9,  customerIntensity: 0.85, aiAgencyNow: 'human',    aiAgencyFuture: 'human',     isPainPoint: true,  isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 63 * 60_000, action: 'Offshore BPO agent handling UK disruption calls has no access to real-time UK operations data. Reading from a disruption policy PDF that is 3 weeks out of date. Customer on the call has more current information via the app.', context: 'Time zone gap: Manila team covers overnight UK window with 8-hour delay in receiving ops updates. No live data feed to offshore sites.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_010', actor: 'Customer Service Agent',       stage: 'Check-in',                 sentiment: 'neutral',   businessIntensity: 0.45, customerIntensity: 0.5,  aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: false, isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 60 * 60_000, action: 'Hyderabad agent handles a seat upgrade request. Amadeus access is granted but fare rules are not visible — agent must refer to team leader after 3 minutes, adding handling time and creating a queue behind them.', context: 'BPO agents have restricted system permissions. Fare rule access requires a separate legacy terminal not available at offshore sites.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_011', actor: 'Workforce Management (WFM)',   stage: 'In-Flight Experience',     sentiment: 'concerned', businessIntensity: 0.95, customerIntensity: 0.7,  aiAgencyNow: 'human',    aiAgencyFuture: 'autonomous',isPainPoint: true,  isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 58 * 60_000, action: 'Erlang C staffing model collapses during disruption — planned for 800 contacts, actual demand reaches 2,400 within 90 minutes. WFM tool cannot dynamically redistribute BPO capacity across sites. Average wait time reaches 45 minutes.', context: 'No real-time demand signal between ops and workforce planning. Disruption volume cannot be anticipated or absorbed by current model.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_012', actor: 'Operations Manager',           stage: 'In-Flight Experience',     sentiment: 'critical',  businessIntensity: 0.95, customerIntensity: 0.8,  aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: true,  isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 55 * 60_000, action: 'Operations manager receives disruption alert 18 minutes after passengers discover the cancellation via the app. No unified notification system connects live ops to contact centre — agent team finds out via internal group chat.', context: 'Structural gap: flight operations systems and contact centre systems are entirely disconnected. Manual relay of disruption information through management chain.', phaseAdded: 'CONSTRAINTS' },
        { id: 'ji_013', actor: 'Corporate Travel Booker',      stage: 'Booking',                  sentiment: 'neutral',   businessIntensity: 0.5,  customerIntensity: 0.45, aiAgencyNow: 'human',    aiAgencyFuture: 'autonomous',isPainPoint: false, isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 52 * 60_000, action: 'Corporate booker managing 15 business travellers calls to modify a group itinerary. Agent cannot batch-process changes — each booking requires a separate transaction and separate call reference. Total call time 34 minutes.', context: 'Corporate accounts represent 28% of revenue. No group-booking management capability in the contact centre platform.', phaseAdded: 'REIMAGINE' },
        { id: 'ji_014', actor: 'IT & Digital Platforms',       stage: 'Booking',                  sentiment: 'positive',  businessIntensity: 0.6,  customerIntensity: 0.55, aiAgencyNow: 'assisted', aiAgencyFuture: 'autonomous',isPainPoint: false, isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 48 * 60_000, action: 'New API middleware layer deployed for digital booking confirmation. Contact centre sees a 12% reduction in "where is my booking" calls within 2 weeks of go-live. Digital self-service is working for this use case.', context: 'Early-stage API integration programme. Booking confirmation is the first use case to go live. 7 further integrations planned for Q2.', phaseAdded: 'DEFINE_APPROACH' },
        { id: 'ji_015', actor: 'Training & Enablement',        stage: 'Check-in',                 sentiment: 'concerned', businessIntensity: 0.7,  customerIntensity: 0.65, aiAgencyNow: 'human',    aiAgencyFuture: 'assisted',  isPainPoint: false, isMomentOfTruth: false, addedBy: 'ai', sourceNodeIds: [], createdAtMs: now - 45 * 60_000, action: 'Newly onboarded agent placed on check-in call queue after 6-week training. Programme did not cover disruption-adjacent check-in scenarios. First live contact of this type results in a 12-minute call with 3 escalations and a frustrated customer.', context: 'Training programme designed 4 years ago. Has not been updated to reflect current contact mix — 38% of contacts now have a disruption or delay element.', phaseAdded: 'CONSTRAINTS' },
      ];
      // Compute mentionCount per actor from interactions
      const mentionMap: Record<string, number> = {};
      for (const ix of interactions) mentionMap[ix.actor] = (mentionMap[ix.actor] ?? 0) + 1;
      const liveActors = blueprintActors.map(a => ({
        ...a,
        mentionCount: (mentionMap[a.name] ?? 0) * 8, // ~8 session mentions per interaction
      }));
      return {
        stages: blueprintStages,
        actors: liveActors,
        interactions,
      };
    })(),
    sessionConfidence: {
      overallConfidence: 0.84,
      categorisedRate: 0.91,
      lensCoverageRate: 0.88,
      contradictionCount: 2,
      stabilisedBeliefCount: 14,
    },
    themes: [],
    activeThemeId: null,
    lensCoverage: [],
    agentConversation: [
      {
        timestampMs: now - 90 * 60_000,
        agent: 'orchestrator',
        to: 'facilitator',
        message: 'Session opened. REIMAGINE phase initiated. 5 main questions loaded.',
        type: 'handoff',
      },
      {
        timestampMs: now - 30 * 60_000,
        agent: 'orchestrator',
        to: 'facilitator',
        message: 'Transitioned to DEFINE_APPROACH. Strong coverage across all 8 lenses in REIMAGINE and CONSTRAINTS.',
        type: 'acknowledgement',
      },
      {
        timestampMs: now - 5 * 60_000,
        agent: 'facilitation-agent',
        to: 'orchestrator',
        message: 'Q4 (BPO Partnership) is active. 2 sub-questions open. Coverage at 62%. Recommend probing the Manila site governance gap.',
        type: 'instruction',
      },
    ],
    journeyCompletionState: null,
    customLensColors: null,
  };

  const payloadStr = JSON.stringify(sessionPayload);

  await (prisma as unknown as { liveSessionVersion: { deleteMany: (a: unknown) => Promise<unknown>; create: (a: unknown) => Promise<{ id: string }> } })
    .liveSessionVersion.create({
      data: {
        workshopId: WORKSHOP_ID,
        version: 1,
        dialoguePhase: 'DEFINE_APPROACH',
        label: 'Full workshop demo — DEFINE_APPROACH Q4/5',
        payload: sessionPayload,
        sizeBytes: Buffer.byteLength(payloadStr, 'utf8'),
      },
    });

  console.log('   ✅ LiveSessionVersion created (v1 — DEFINE_APPROACH, Q4 active)\n');

  // ── Summary ───────────────────────────────────────────────────────────────────
  console.log('═══════════════════════════════════════════════════════');
  console.log('✅ Jo Air dense seed complete');
  console.log('═══════════════════════════════════════════════════════');
  console.log(`   Hemisphere nodes : ${nodeIdx} (${phaseCounts.REIMAGINE} R + ${phaseCounts.CONSTRAINTS} C + ${phaseCounts.DEFINE_APPROACH} D)`);
  console.log(`   Main questions   : ${mainQs.length} (DEFINE_APPROACH)`);
  console.log(`   Covered pads     : ${completedByQuestion.reduce((s, [, p]) => s + p.length, 0)} (Q0–Q3)`);
  console.log(`   Active pads      : ${stickyPads.filter(p => p.coverageState === 'active').length} (Q4)`);
  console.log(`   Covered in Q4    : ${stickyPads.filter(p => p.coverageState === 'covered').length}`);
  console.log('');
  console.log('👉 Navigate to the Jo Air cognitive-guidance page — the covered');
  console.log('   tab will auto-populate from this version on first load.');
  console.log('');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
